services:
  rat-clan-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rat-clan-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  rat-clan-network:
    driver: bridge
