version: '3.8'

services:
  rat-clan-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rat-clan-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # Nginx Proxy Manager para SSL (opcional)
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:81'   # Interface de admin
      - '443:443'   # HTTPS
    volumes:
      - npm_data:/data
      - npm_ssl:/etc/letsencrypt
    networks:
      - rat-clan-network
    profiles:
      - ssl

networks:
  rat-clan-network:
    driver: bridge

volumes:
  npm_data:
  npm_ssl: