// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xofpjtphrjzrvsbdkgwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvZnBqdHBocmp6cnZzYmRrZ3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTAxMjksImV4cCI6MjA3Mjk2NjEyOX0.fpsCAJ5ekTH2ygfYSldOELT6_rw3X_DlIPDtiT3UTJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});